tools:
    external_code_coverage:
        timeout: 600    # Timeout in seconds.

coding_style:
    php:
        spaces:
            around_operators:
                concatenation: false
            before_left_brace:
                function: false
